version: '3.9'

services:
  web:
    build: .
    volumes:
      - static:/static
    command: >
      sh -c "
              python manage.py collectstatic --no-input &&
              python manage.py makemigrations &&
              python manage.py migrate
              gunicorn orders.wsgi:application -w 4 -b 0.0.0.0:8000
            "
    ports:
      - "8000:8000"

volumes:
  static: